server:
  port: 8080

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: order-service
          uri: http://127.0.0.1:8081/order
          predicates:
            - Path=/order/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/order/(?<path>.*),/$\{path}

        - id: customer-service
          uri: http://127.0.0.1:8081/customer
          predicates:
            - Path=/customer/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/customer/(?<path>.*),/$\{path}

        - id: kitchen-service
          uri: http://127.0.0.1:8082/kitchen
          predicates:
            - Path=/kitchen/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/kitchen/(?<path>.*),/$\{path}

        - id: restaurant-service
          uri: http://127.0.0.1:8082/restaurant
          predicates:
            - Path=/restaurant/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/restaurant/(?<path>.*),/$\{path}

        - id: courier-service
          uri: http://127.0.0.1:8083/courier
          predicates:
            - Path=/courier/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/courier/(?<path>.*),/$\{path}

        - id: delivery-service
          uri: http://127.0.0.1:8083/delivery
          predicates:
            - Path=/delivery/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/delivery/(?<path>.*),/$\{path}

        - id: register
          uri: http://127.0.0.1:9000/register
          predicates:
            - Path=/register/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/register/(?<path>.*),/$\{path}

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid,message.read
        provider:
          spring:
            issuer-uri: http://localhost:9000