delivery-service-feign:
  url: http://localhost:8082


server:
  port: 8082
  servlet:
    context-path:

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS

spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
      org:
        hibernate:
          envers:
            revision_field_name: rev_id
            revision_type_field_name: rev_type
    show-sql: 'true'
  datasource:
    password: 'root'
    url: jdbc:postgresql://localhost:5432/food_service

    username: 'postgres'